/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_terms` VALUES
(1,"Uncategorized","uncategorized",0),
(2,"News","news",0),
(3,"Business","business",0),
(4,"Politics","politics",0),
(5,"Science","science",0),
(6,"World","world",0),
(7,"Lifestyle","lifestyle",0),
(8,"Fashion","fashion",0),
(9,"Travel","travel",0),
(10,"Food","food",0),
(11,"Health","health",0),
(12,"Tech","tech",0),
(13,"Apps","apps",0),
(14,"Gadget","gadget",0),
(15,"Mobile","mobile",0),
(16,"Startup","startup",0),
(17,"Entertainment","entertainment",0),
(18,"Gaming","gaming",0),
(19,"Movie","movie",0),
(20,"Music","music",0),
(21,"Sports","sports",0),
(22,"Review","review",0),
(23,"Trump Inauguration","trump-inauguration",0),
(24,"United Stated","united-stated",0),
(25,"Election Results","election-results",0),
(26,"White House","white-house",0),
(27,"Market Stories","market-stories",0),
(28,"Fashion Week","fashion-week",0),
(29,"Golden Globes","golden-globes",0),
(30,"Game of Thrones","game-of-thrones",0),
(31,"MotoGP 2017","motogp-2017",0),
(32,"eSports","esports",0),
(33,"CES 2017","ces-2017",0),
(34,"Nintendo Switch","nintendo-switch",0),
(35,"Mark Zuckerberg","mark-zuckerberg",0),
(36,"Sillicon Valley","sillicon-valley",0),
(37,"Playstation 4 Pro","ps4-pro",0),
(38,"post-format-video","post-format-video",0),
(39,"post-format-gallery","post-format-gallery",0),
(40,"Main Navigation","main-navigation",0),
(41,"Mobile Navigation","mobile-navigation",0),
(42,"Footer Navigation","footer-navigation",0);
