/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
/*!40103 SET TIME_ZONE='+00:00' */;
INSERT INTO `wp_term_taxonomy` VALUES
(1,1,"category","",0,0),
(2,2,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",0,6),
(3,3,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",2,18),
(4,4,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",2,18),
(5,5,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",2,10),
(6,6,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",2,16),
(7,7,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",0,9),
(8,8,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",7,18),
(9,9,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",7,18),
(10,10,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",7,10),
(11,11,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",7,15),
(12,12,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",0,2),
(13,13,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",12,12),
(14,14,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",12,22),
(15,15,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",12,18),
(16,16,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",12,17),
(17,17,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",0,1),
(18,18,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",17,14),
(19,19,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",17,9),
(20,20,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",17,11),
(21,21,"category","A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart.",17,14),
(22,22,"category","We brings you detailed expert reviews and ratins of the latest consumer electronics, tech products, along with specs, user reviews, prices and more.",0,7),
(23,23,"post_tag","",0,18),
(24,24,"post_tag","",0,22),
(25,25,"post_tag","",0,24),
(26,26,"post_tag","",0,23),
(27,27,"post_tag","",0,21),
(28,28,"post_tag","",0,29),
(29,29,"post_tag","",0,28),
(30,30,"post_tag","",0,19),
(31,31,"post_tag","",0,31),
(32,32,"post_tag","",0,23),
(33,33,"post_tag","",0,31),
(34,34,"post_tag","",0,19),
(35,35,"post_tag","",0,30),
(36,36,"post_tag","",0,19),
(37,37,"post_tag","",0,27),
(38,38,"post_format","",0,6),
(39,39,"post_format","",0,3),
(40,40,"nav_menu","",0,12),
(41,41,"nav_menu","",0,0),
(42,42,"nav_menu","",0,4);
